### ISSUE TITLE
Compatibility with autocomplete

### ISSUE THREAD

**Issue by Chris3606** [click-contrib/click-option-group#14]
I could be wrong, but I believe the method the option groups such as `RequiredMutuallyExclusiveOptionGroup` use to check for duplicates (by throwing exceptions in the `handle_parse_result` function) may render them incompatible with click's BASH autocomplete function.  During the generation of completion results, as part of `click._bashcomplete.resolve_ctx()`, it evaluates the options of each command.  Since completion is running before the user has typed the full command, the option throws an exception (because the required argument isn't there), and crashes the completion script.

The issue I actually ran into was attempting to use this with [click-repl](https://github.com/click-contrib/click-repl), and in this instance it definitely crashes.  It's autocomplete uses prompt-toolkit's infrastructure, but the actual completion code leverages the same methods used in bash autocomplete (in fact it calls `click._bashcomplete.resolve_ctx()` just click click's actual BASH autocompletion support does).

This might just be an incompatibility that can't easily be remedied, but I wanted to bring it up, as being able to use click-option-group in these instances could be really useful.  Is this something you're interested in supporting?  Is it something that even can be supported, or does it require an entirely different approach for validating arguments?

**Comment by espdev** [comment]
@Chris3606 thanks for the report!

I will investigate the issue and I will think what can be done about it.

**Comment by espdev** [comment]
@Chris3606 could you check auto-completion functionality (also in click-repl) with the latest changes from master branch?

**Comment by Chris3606** [comment]
Seems to work now, although it shows as an option in autocomplete the "fake" click option used by the option group:
![image](https://user-images.githubusercontent.com/6090062/84578551-f32b9300-ad8b-11ea-934e-670a09e0fae5.png)

There probably isn't much that can be done about that, I think I could just write a custom completer that accounts for the option groups properly.  Thank you!

**Comment by espdev** [comment]
Yes, I also checked with click-repl. It seems to me click-repl completer shows the hidden options (it ignores "hidden" option flag). In this case "fake" option will be shown also. That is not good, but I do not know how we can fix it without change click-repl code.  Generally I don't like the idea of ​​using "fake" options in click-option-group, and maybe I will redo it sometime.

**Comment by Chris3606** [comment]
No problem, In my particular use case, click-repl was just the code base I started with, and I already have a custom completer currently (which click-option-group also works with after the update), so I can just modify the implementation.

The other thing I noticed is the autocomplete will still suggest mutually exclusive options after one has already been entered: when `test --param1 5 ` is typed it still suggests `--param2`, but since click-repl has no way to be aware of the special conditions surrouding click-option-groups, there's not much that can be done about this either without touching click-repl code.  It should be at least reasonable to write a custom completer that can handle this too though (I'll likely find out over the next few days), so it's not a complete incompatibility.  Thanks again!

**Comment by espdev** [comment]
Link to the issue about hidden options in click-repl: https://github.com/click-contrib/click-repl/issues/64

**Comment by espdev** [comment]
@Chris3606 it seems it works now with default click-repl completion
![2020-06-14_23-09-48](https://user-images.githubusercontent.com/1299189/84603098-6c161200-ae94-11ea-961a-84d2f43cf5a5.png)

I make a new release with these changes soon.

**Comment by espdev** [comment]
done
https://pypi.org/project/click-option-group/0.5.1/
