### ISSUE TITLE
The package does not support Python 3.5

### ISSUE THREAD

**Issue by andy-maier** [click-contrib/click-option-group#17]
Python 3.5 is still officially supported.

**Comment by espdev** [comment]
Hello @andy-maier,

Official support of Python 3.5 will have been ended by 2020-09-13. Currently, security fixes are only available, no bug fixes are provided. Thus, Python 3.5 won't be supported. I'm sorry for any inconveniences caused. 

I recommend you use Python 3.6 as a minimal version of modern Python.
