### ISSUE TITLE
No test files in sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [click-contrib/click-option-group#39]
Hi! I'm packaging this for Arch Linux. We usually rely on sdist tarballs on pypi.org and run the tests of each project (if possible) that we package.

Unfortunately the tests are missing from the sdist tarball and I have to revert to using the auto-generated tarball on github (which is also possible for me to use). However, would it be possible for you to add the tests also to the sdist tarball? Thanks! :)

**Comment by espdev** [comment]
Hi @dvzrv,

There is no difficulty in adding tests directory to sdist. I can just update `MANIFEST.in` file and make a new release. However, pytest package is required to run tests. Install target do not install dependencies for testing. Currently, we have extra dependencies (`extras_require`) `tests` to install pytest and other packages for testing.

**Comment by espdev** [comment]
For now, I'm closing the issue. Please let me know if this is still important to someone.

**Comment by espdev** [comment]
`tests` directory was added in 0.5.5 release
https://pypi.org/project/click-option-group/0.5.5/
