### ISSUE TITLE
Question: mutualy exclusive groups

### ISSUE THREAD

**Issue by nikoladsp** [click-contrib/click-option-group#46]
Hi,
a question: how to make multiple groups mutually exclusive (if possible)?

So say I have group1 with options opt11 and opt12 and group2 with options opt21 and opt22. I want to force one group to exclude another: if I set opt11 and opt12, then opt21 and opt22 should not be set.

Thank you in advance.

Kindest regards

**Comment by espdev** [comment]
Hi @nikoladsp,

Any constraints between option groups are currently not supported. In your case, subgroups are needed, but subgroups are not supported either. 

Please look at [cloup](https://github.com/janluke/cloup) project.

**Comment by nikoladsp** [comment]
Thank you
